### ISSUE TITLE
Kicad files

### ISSUE THREAD

**Issue by KeLaiFu** [squaresolid/benjolin_gorga#1]
First of all, thanks for reworking this design, you did a great job and this was something I was playing around with in Kicad myself so I know it can be very time consuming.

Would it be possible for you to share the actual kicad files so I can add a few tweaks to my preference (mainly the spacing of the pots in relation to the right side of the panel)

Thanks again!

**Comment by squaresolid** [comment]
Hey KeLaiFu!

Thanks for let me know. I was doing the Kicad with my wife's laptop at the Hospital, and I thought I uploaded all the files up on Github. It seems maybe the connections stopped or I forgot or whatever. Now it's there, have fun tweaking it and let me know if you're printing one, because I haven't. I will order it soon too! Thanks again!
